/* Action constants */

const Actions = {}

//Todo actions
Actions.ADD_TODO = 'ADD_TODO'
Actions.MARK_AS_COMPLETE = 'MARK_AS_COMPLETE'
Actions.UNDO_COMPLETE = 'UNDO_COMPLETE'
Actions.CLEAR_COMPLETED = 'CLEAR_COMPLETED'


//User actions
Actions.CREATE_USER = 'CREATE_USER'
Actions.CREATE_USER_SUCCESS= 'CREATE_USER_SUCCESS'
Actions.CREATE_USER_ERROR='CREATE_USER_ERROR'

Actions.GET_USER = 'GET_USER'
Actions.GET_USER_SUCCESS= 'GET_USER_SUCCESS'
Actions.GET_USER_ERROR='GET_USER_ERROR'

Actions.UPDATE_USER = 'UPDATE_USER'
Actions.UPDATE_SUCCESS= 'UPDATE_USER_SUCCESS'
Actions.UPDATE_ERROR='UPDATE_USER_ERROR'

export default Actions